name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run:  docker build -t ashinamanulla/test-node .

      - name: Publish image to docker hub
        run:  docker push ashinamanulla/test-node:latest

  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Pull image from docker hub
        run: docker pull ashinamanulla/test-node:latest
        
      - name: Delete old container
        run: docker rm -f test-node-container

      - name: Run docker container
        run: docker run -d -p 5000:5000 --name test-node-container ashinamanulla/test-node
     
